### ISSUE TITLE
namespace::autoclean dependency undeclared

### ISSUE THREAD

**Issue by andk** [doriantaylor/p5-role-mimeinfo#1]
As per subject. Grep:

http://search.cpan.org/grep?release=Role-MimeInfo-0.01;string=namespace::autoclean;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/87068546

HTH&&Thanks,

**Comment by doriantaylor** [comment]
ah yes thanks; always forgetting that
