### ISSUE TITLE
Purpose of role?

### ISSUE THREAD

**Issue by Grinnz** [doriantaylor/p5-role-mimeinfo#2]
The methods in this role do not appear to have any interaction with the invocant at all. They do appear to provide some functionality over the File::MimeInfo functions they wrap so maybe this added value should be explained in docs? But I don't see a reason these shouldn't just be exported functions.

(By the way namespace::autoclean and such are unnecessary for Moo::Role roles. See https://metacpan.org/pod/Moo::Role#CLEANING-UP-IMPORTS)

**Comment by doriantaylor** [comment]
Indeed it does not interact with the invocant (yet). One could argue that really this module should be a PR against File::MimeInfo. This module exists because I found myself copying/pasting the same recursive `mimetype_isa` function over and over in about 4 or 5 different places (the original is considerably less robust). I found myself unable to sleep one night so now it exists. Should it not?

As for namespace::autoclean, I will concede that it's in there largely because it is Moose detritus.

**Comment by Grinnz** [comment]
I'm not saying it shouldn't exist, just that the functions would be more generally usable if they were regular exportable functions, instead of needing to be applied as a role to a class and then called as methods, when that isn't currently required for the functions to work. But if you have plans for methods to use the invocant then that would make sense.

**Comment by doriantaylor** [comment]
I consider it a hedge in some regard. All my own Perl programming for the foreseeable future will be under some MOP or other, and I do a lot of stuff with MIME types. Moreover it was 3 in the morning and I just wanted to get things done and not deal with the politics of an upstream patch, no matter how painless that may turn out to be.

I agree that this functionality ultimately belongs in the original File::MimeInfo, though it does subtly change the behaviour of those functions (in particular, tests that would have once returned false would now return true). I suppose I could release some _other_ function-interface module, but then that would entail putting more thought into it than just banging out a Role in the middle of the night. I certainly wouldn't want to do that without first discussing a patch with the upstream maintainer, which, now that my own immediate needs have been taken care of, I am free to explore.

If I can negotiate a patch to File::MimeInfo then yes I will probably deprecate this module.
